### ISSUE TITLE
Error when building branch R3_7_maintenance with Maven

### ISSUE THREAD

**Issue by trifonnt** [eclipse-acceleo/acceleo#122]
**Environment:** 
openjdk version "**17.0.8.1**" 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu120.04, mixed mode, sharing)

Apache Maven **3.6.3** (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven-3.6.3
Java version: 17.0.8.1, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-166-generic", arch: "amd64", family: "unix"

Acceleo branch "R3_7_maintenance" 

When trying to build Acceleo via Maven I got:
`[ERROR] Failed to resolve target definition file:/home/vagrant/workspace-eclipse-dsl-2023-06/acceleo/releng/org.eclipse.acceleo.targetplatforms/2023-03/acceleo-2023-03.target: Failed to load p2 metadata repository from location https://download.eclipse.org/eclipse/updates/4.28-I-builds/: No repository found at https://download.eclipse.org/eclipse/updates/4.28-I-builds.`

**Comment by pcdavid** [comment]
Should be fixed by https://github.com/eclipse-acceleo/acceleo/pull/124/commits/472fe02488fb6a2fa1c106bba2270b942828e44c

**Comment by trifonnt** [comment]
> Should be fixed by [472fe02](https://github.com/eclipse-acceleo/acceleo/commit/472fe02488fb6a2fa1c106bba2270b942828e44c)

Thank you!
It works now!

**Comment by Kellindil** [comment]
The previous target platform was using an I build of the platform in order to fix one of the API breakages we had to cope with at that time and hadn't been updated.

I've abandonned the PR from @pcdavid since I missed it, but pushed a new target platform on the repository to uses the latest 2023-12 dependencies so you will no longer encounter this with the laster R3_7_maintenance tip either (https://github.com/eclipse-acceleo/acceleo/pull/125/files#diff-3989a4fb9cc42366c1f194aea0705a826b216859cfe3e4fd22ae5053b6439d84)
