### ISSUE TITLE
First two letters are cut off on each line

### ISSUE THREAD

**Issue by AresEkb** [eclipse-acceleo/acceleo#180]
Here is a sample template:

```
[comment encoding = UTF-8 /]

[module test('http://www.eclipse.org/emf/2002/Ecore')/]

[comment @main/]
[template public generate(model : ecore::EPackage)]
Begin
[model/]
End
[/template]
```

The result is:
```
gin
org.eclipse.emf.ecore.impl.EPackageImpl@100d7815 (name: testpkg) (nsURI: null, nsPrefix: null)
d
```

First two letters are removed from "Begin" and "End"

I think it's because of [the following line](https://github.com/eclipse-acceleo/acceleo/blob/9155176ef82f81a6196ccf8587f7aad0fc49bcef/plugins/org.eclipse.acceleo.aql/src/org/eclipse/acceleo/aql/parser/AcceleoParser.java#L1442):
```
final int significantTextColumn = columns[startPosition] + INDENTATION;
```

Also I guess that `[comment @main/]` should be inside `[template]`. But the template is not recignized as the main one in that case.

**Comment by ylussaud** [comment]
If you are familiar with Acceleo 3 there are a few changes with Acceleo 4:

* OCL has been replaced with [AQL](https://github.com/eclipse-acceleo/acceleo/blob/master/query/plugins/org.eclipse.acceleo.query.doc/input/index.textile) (for services references you can also have a look at [this page](https://eclipse.dev/acceleo/documentation/aql.html) the other page should soon includes service references).
* The indentation policy has changed to introduce mandatory indentation in the template that can be distinguished from the indentation in the generated document. Also blocks of code are inserted in a way they keep the caller indentation by repeating the last generated line if needed. You can find more details [here](https://github.com/eclipse-acceleo/acceleo/blob/master/plugins/org.eclipse.acceleo.aql.doc/pages/language.adoc#white-spaces). This explains the two first characters that are not in the generated output.
* The compilation to emtl has been removed.
* The main comment moved outside of the template (I though it was also the case in Acceleo 3...).

For more details about Acceleo 4, you can check the [documentation](https://github.com/eclipse-acceleo/acceleo/blob/master/plugins/org.eclipse.acceleo.aql.doc/toc.adoc). If you are migrating from Acceleo 3 check the [migration section](https://github.com/eclipse-acceleo/acceleo/blob/master/plugins/org.eclipse.acceleo.aql.doc/pages/migration.adoc) that also incluse more details on changes between Acceleo 3 and 4.

Also note that since the first release of Acceleo 4 we have been busy fixing a wide range of small annoying bugs and improve user experience (there is now an error marker and a quick fix when the template indentation is missing). Those fixes are not release yet but you can benefit from them by using the [last nightly build](https://download.eclipse.org/acceleo/updates/nightly/latest/). A new release 4.1.0 should be available soon, probably at the beginning of next year.

Hope that will help you get started with Acceleo 4, if you have other questions don't hesitate to ask them.

**Comment by AresEkb** [comment]
Thanks for the links and desciption, I've got it now!
